import { getChatGPTUser } from '../../chatgpt-auth';
import { database, roomFor } from '@/db/store';
import { initialState, mutate } from '../../domain';
const reply=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(){try{const user=await getChatGPTUser();if(!user)return reply({user:null,room:null});const room=await roomFor(user.userId);return reply({user:{id:user.userId,name:user.displayName,email:user.email},room:room?{id:room.id,role:room.owner===user.userId?'owner':'partner',paired:!!room.partner,code:room.owner===user.userId?room.code:null,state:JSON.parse(room.state)}:null});}catch(e){console.error('space load',e);return reply({error:'暂时无法加载空间，请稍后重试'},503)}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'请先登录'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'请求来源无效'},403);const raw=await req.text();if(raw.length>30000)return reply({error:'提交的内容过长'},413);const b=JSON.parse(raw);const db=database();let room=await roomFor(user.userId);
if(b.action==='createRoom'){if(room)return reply({message:'你已经有一个双人空间'});const id=crypto.randomUUID(),code=crypto.randomUUID().replaceAll('-','');const s=initialState(String(b.ownerName||'主人').slice(0,24));s.partnerName=String(b.partnerName||'小伙伴').slice(0,24);await db.batch([db.prepare('INSERT INTO rooms(id,owner,code,state,version) VALUES(?,?,?,?,0)').bind(id,user.userId,code,JSON.stringify(s)),db.prepare('INSERT INTO members(user_id,room_id) VALUES(?,?)').bind(user.userId,id)]);return reply({message:'双人空间已创建'});}
if(b.action==='joinRoom'){if(room)return reply({error:'你已加入一个空间，不能重复加入'},400);const code=String(b.code||'').trim();const target=await db.prepare('SELECT id,owner,partner FROM rooms WHERE code=?').bind(code).first<any>();if(!target||target.partner)return reply({error:'邀请码无效，或这个空间已经配对'},400);if(target.owner===user.userId)return reply({error:'请让小伙伴用自己的账号加入'},400);const results=await db.batch([db.prepare('UPDATE rooms SET partner=?,version=version+1 WHERE id=? AND partner IS NULL').bind(user.userId,target.id),db.prepare('INSERT INTO members(user_id,room_id) SELECT ?,id FROM rooms WHERE id=? AND partner=?').bind(user.userId,target.id,user.userId)]);if(!results[0].meta.changes)return reply({error:'这个空间刚刚被另一位伙伴加入了'},409);return reply({message:'配对成功，欢迎来到我们的空间'});}
if(!room)return reply({error:'请先创建或加入空间'},400);if(!/^[0-9a-f-]{36}$/i.test(b.requestId||''))return reply({error:'请求编号无效，请重新操作'},400);
for(let attempt=0;attempt<3;attempt++){const old=await db.prepare('SELECT result FROM operations WHERE id=? AND room_id=? AND user_id=?').bind(b.requestId,room.id,user.userId).first<any>();if(old)return reply(JSON.parse(old.result));const role=room.owner===user.userId?'owner':'partner';if(b.action==='submit'){b.files=Array.isArray(b.files)?b.files:[];const safe=[];for(const f of b.files){const file=await db.prepare('SELECT id,name,type FROM uploads WHERE id=? AND room_id=? AND user_id=?').bind(String(f.id),room.id,user.userId).first<any>();if(!file)return reply({error:'凭证文件不存在或无权使用'},400);safe.push(file)}b.files=safe;}
const {state,result}=mutate(JSON.parse(room.state),role,b.action,b,undefined,()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296);const serialized=JSON.stringify(state);if(serialized.length>700000)return reply({error:'空间记录已达到容量上限，请联系管理员导出整理'},400);
const updated=await db.batch([db.prepare('INSERT INTO operations(id,room_id,user_id,result) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM rooms WHERE id=? AND version=?)').bind(b.requestId,room.id,user.userId,JSON.stringify(result),room.id,room.version),db.prepare('UPDATE rooms SET state=?,version=version+1 WHERE id=? AND version=?').bind(serialized,room.id,room.version)]);if(updated[1].meta.changes)return reply(result);room=await roomFor(user.userId);}
return reply({error:'双方刚刚同时修改了空间，请刷新后重试'},409);
}catch(e:any){console.error('space mutation',e);const known=e instanceof Error&&!/SQLITE|D1_|binding|constraint|JSON/i.test(e.message);return reply({error:known?e.message:'保存失败，请刷新确认结果后重试'},400)}}
